sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ajbacon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ajbacon/react-test npm test

after_success:
  - docker build -t ajbacon/fib-client ./client
  - docker build -t ajbacon/fib-nginx ./nginx
  - docker build -t ajbacon/fib-server ./server
  - docker build -t ajbacon/fib-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push ajbacon/fib-client
  - docker push ajbacon/fib-nginx 
  - docker push ajbacon/fib-server
  - docker push ajbacon/fib-worker

